### ISSUE TITLE
Possible for reload triggers?

### ISSUE THREAD

**Issue by mrc4tt** [bonnici/node-steam-chat-bot#12]
Hi.

Is there someway possible for reload (updated triggers) without to shutdown/pull script offline and restart it anytime?

**Comment by mrc4tt** [comment]
@bonnici - maybe you have some idea?

**Comment by bonnici** [comment]
It's been a while since I looked at this but me-from-the-past said that this should work:

```
// Trigger details can be retrieved and reloaded so that external configuration can be supported
var details = myBot.getTriggerDetails();
myBot.clearTriggers();
myBot.addTriggers(details);
```

**Comment by mrc4tt** [comment]
@bonnici - Hmm.. so if i change on: (as example: `var triggers = require("./examples/example-config-triggers2.js");` (the .js file) - how should i get it "reload" after changes?

**Comment by bonnici** [comment]
I'm just looking through the code again. If you call `addTrigger`, it will reload the trigger's js file and remove and re-add it, so it will be using the latest code. It also looks like you can just call `addTrigger` if you add a new js file. It doesn't watch the files though so it won't automatically reload trigger config after you change a file. You'd need to write some code to do that, maybe even a new "reload triggers" trigger would work.
